import { REFERENCES } from './references'

// 出典: docs/nsfactory/data/timber-fc.json（HOWTEC 2025-12版）
export interface TimberFc {
  standard: string
  species: string
  grade: string
  fc: number
}
export const TIMBER_FC_SOURCE =
  'HOWTEC 在来軸組工法用 表計算ツール（2025-12版）シート『柱の圧縮基準強度』。圧縮基準強度 Fc（N/mm²）'
export const TIMBER_FC_REFERENCES = [REFERENCES.howtec] as const
export const TIMBER_FC: readonly TimberFc[] = [
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'あかまつ',
    grade: 'E70',
    fc: 9.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'あかまつ',
    grade: 'E90',
    fc: 16.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'あかまつ',
    grade: 'E110',
    fc: 24.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'あかまつ',
    grade: 'E130',
    fc: 31.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'あかまつ',
    grade: 'E150',
    fc: 39.0,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'べいまつ',
    grade: 'E70',
    fc: 9.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'べいまつ',
    grade: 'E90',
    fc: 16.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'べいまつ',
    grade: 'E110',
    fc: 24.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'べいまつ',
    grade: 'E130',
    fc: 31.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'べいまつ',
    grade: 'E150',
    fc: 39.0,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ダフリカからまつ',
    grade: 'E70',
    fc: 9.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ダフリカからまつ',
    grade: 'E90',
    fc: 16.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ダフリカからまつ',
    grade: 'E110',
    fc: 24.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ダフリカからまつ',
    grade: 'E130',
    fc: 31.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ダフリカからまつ',
    grade: 'E150',
    fc: 39.0,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'べいつが',
    grade: 'E70',
    fc: 9.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'べいつが',
    grade: 'E90',
    fc: 16.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'べいつが',
    grade: 'E110',
    fc: 24.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'べいつが',
    grade: 'E130',
    fc: 31.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'べいつが',
    grade: 'E150',
    fc: 39.0,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'えぞまつ',
    grade: 'E70',
    fc: 9.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'えぞまつ',
    grade: 'E90',
    fc: 16.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'えぞまつ',
    grade: 'E110',
    fc: 24.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'えぞまつ',
    grade: 'E130',
    fc: 31.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'えぞまつ',
    grade: 'E150',
    fc: 39.0,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'とどまつ',
    grade: 'E70',
    fc: 9.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'とどまつ',
    grade: 'E90',
    fc: 16.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'とどまつ',
    grade: 'E110',
    fc: 24.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'とどまつ',
    grade: 'E130',
    fc: 31.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'とどまつ',
    grade: 'E150',
    fc: 39.0,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'からまつ',
    grade: 'E50',
    fc: 11.4,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'からまつ',
    grade: 'E70',
    fc: 18.0,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'からまつ',
    grade: 'E90',
    fc: 24.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'からまつ',
    grade: 'E110',
    fc: 31.2,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'からまつ',
    grade: 'E130',
    fc: 37.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'からまつ',
    grade: 'E150',
    fc: 44.4,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ひのき',
    grade: 'E50',
    fc: 11.4,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ひのき',
    grade: 'E70',
    fc: 18.0,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ひのき',
    grade: 'E90',
    fc: 24.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ひのき',
    grade: 'E110',
    fc: 31.2,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ひのき',
    grade: 'E130',
    fc: 37.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ひのき',
    grade: 'E150',
    fc: 44.4,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ひば',
    grade: 'E50',
    fc: 11.4,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ひば',
    grade: 'E70',
    fc: 18.0,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ひば',
    grade: 'E90',
    fc: 24.6,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ひば',
    grade: 'E110',
    fc: 31.2,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ひば',
    grade: 'E130',
    fc: 37.8,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'ひば',
    grade: 'E150',
    fc: 44.4,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'すぎ',
    grade: 'E50',
    fc: 19.2,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'すぎ',
    grade: 'E70',
    fc: 23.4,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'すぎ',
    grade: 'E90',
    fc: 28.2,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'すぎ',
    grade: 'E110',
    fc: 32.4,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'すぎ',
    grade: 'E130',
    fc: 37.2,
  },
  {
    standard: 'JAS機械等級区分構造用製材',
    species: 'すぎ',
    grade: 'E150',
    fc: 41.4,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'あかまつ',
    grade: '甲種構造材\n乙種構造材',
    fc: 27.0,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'あかまつ',
    grade: '',
    fc: 16.8,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'あかまつ',
    grade: '',
    fc: 11.4,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'べいまつ',
    grade: '甲種構造材\n乙種構造材',
    fc: 27.0,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'べいまつ',
    grade: '',
    fc: 18.0,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'べいまつ',
    grade: '',
    fc: 13.8,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'からまつ',
    grade: '甲種構造材\n乙種構造材',
    fc: 23.4,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'からまつ',
    grade: '',
    fc: 20.4,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'からまつ',
    grade: '',
    fc: 18.6,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'ダフリカからまつ',
    grade: '甲種構造材\n乙種構造材',
    fc: 28.8,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'ダフリカからまつ',
    grade: '',
    fc: 25.2,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'ダフリカからまつ',
    grade: '',
    fc: 22.2,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'ひば',
    grade: '甲種構造材\n乙種構造材',
    fc: 28.2,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'ひば',
    grade: '',
    fc: 27.6,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'ひば',
    grade: '',
    fc: 23.4,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'ひのき',
    grade: '甲種構造材\n乙種構造材',
    fc: 30.6,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'ひのき',
    grade: '',
    fc: 27.0,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'ひのき',
    grade: '',
    fc: 23.4,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'べいつが',
    grade: '甲種構造材\n乙種構造材',
    fc: 21.0,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'べいつが',
    grade: '',
    fc: 21.0,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'べいつが',
    grade: '',
    fc: 17.4,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'えぞまつ及びとどまつ',
    grade: '甲種構造材\n乙種構造材',
    fc: 27.0,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'えぞまつ及びとどまつ',
    grade: '',
    fc: 22.8,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'えぞまつ及びとどまつ',
    grade: '',
    fc: 13.8,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'すぎ',
    grade: '甲種構造材\n乙種構造材',
    fc: 21.6,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'すぎ',
    grade: '',
    fc: 20.4,
  },
  {
    standard: 'JAS目視等級区分構造用製材',
    species: 'すぎ',
    grade: '',
    fc: 18.0,
  },
  {
    standard: '無等級材',
    species: 'あかまつ',
    grade: '針葉樹',
    fc: 22.2,
  },
  {
    standard: '無等級材',
    species: 'くろまつ',
    grade: '',
    fc: 22.2,
  },
  {
    standard: '無等級材',
    species: 'べいまつ',
    grade: '',
    fc: 22.2,
  },
  {
    standard: '無等級材',
    species: 'からまつ',
    grade: '',
    fc: 20.7,
  },
  {
    standard: '無等級材',
    species: 'ひば',
    grade: '',
    fc: 20.7,
  },
  {
    standard: '無等級材',
    species: 'ひのき',
    grade: '',
    fc: 20.7,
  },
  {
    standard: '無等級材',
    species: 'べいひ',
    grade: '',
    fc: 20.7,
  },
  {
    standard: '無等級材',
    species: 'べいひば',
    grade: '',
    fc: 20.7,
  },
  {
    standard: '無等級材',
    species: 'つが',
    grade: '',
    fc: 19.2,
  },
  {
    standard: '無等級材',
    species: 'べいつが',
    grade: '',
    fc: 19.2,
  },
  {
    standard: '無等級材',
    species: 'もみ',
    grade: '',
    fc: 17.7,
  },
  {
    standard: '無等級材',
    species: 'えぞまつ',
    grade: '',
    fc: 17.7,
  },
  {
    standard: '無等級材',
    species: 'とどまつ',
    grade: '',
    fc: 17.7,
  },
  {
    standard: '無等級材',
    species: 'べにまつ',
    grade: '',
    fc: 17.7,
  },
  {
    standard: '無等級材',
    species: 'すぎ',
    grade: '',
    fc: 17.7,
  },
  {
    standard: '無等級材',
    species: 'べいすぎ',
    grade: '',
    fc: 17.7,
  },
  {
    standard: '無等級材',
    species: 'スプルース',
    grade: '',
    fc: 17.7,
  },
  {
    standard: '無等級材',
    species: 'かし',
    grade: '広葉樹',
    fc: 27.0,
  },
  {
    standard: '無等級材',
    species: 'くり',
    grade: '',
    fc: 21.0,
  },
  {
    standard: '無等級材',
    species: 'なら',
    grade: '',
    fc: 21.0,
  },
  {
    standard: '無等級材',
    species: 'ぶな',
    grade: '',
    fc: 21.0,
  },
  {
    standard: '無等級材',
    species: 'けやき',
    grade: '',
    fc: 21.0,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(4層以上)',
    grade: 'E190',
    fc: 50.3,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(4層以上)',
    grade: 'E170',
    fc: 44.6,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(4層以上)',
    grade: 'E150',
    fc: 39.2,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(4層以上)',
    grade: 'E135',
    fc: 33.4,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(4層以上)',
    grade: 'E120',
    fc: 30.1,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(4層以上)',
    grade: 'E105',
    fc: 28.1,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(4層以上)',
    grade: 'E95',
    fc: 26.0,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(4層以上)',
    grade: 'E85',
    fc: 24.3,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(4層以上)',
    grade: 'E75',
    fc: 22.3,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(4層以上)',
    grade: 'E65',
    fc: 20.6,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(4層以上)',
    grade: 'E55',
    fc: 18.6,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(3層)',
    grade: 'E190',
    fc: 45.8,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(3層)',
    grade: 'E170',
    fc: 40.5,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(3層)',
    grade: 'E150',
    fc: 35.6,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(3層)',
    grade: 'E135',
    fc: 30.4,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(3層)',
    grade: 'E120',
    fc: 27.4,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(3層)',
    grade: 'E105',
    fc: 25.5,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(3層)',
    grade: 'E95',
    fc: 23.6,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(3層)',
    grade: 'E85',
    fc: 22.1,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(3層)',
    grade: 'E75',
    fc: 20.3,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(3層)',
    grade: 'E65',
    fc: 18.8,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(3層)',
    grade: 'E55',
    fc: 16.9,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(2層)',
    grade: 'E190',
    fc: 45.8,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(2層)',
    grade: 'E170',
    fc: 40.5,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(2層)',
    grade: 'E150',
    fc: 35.6,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(2層)',
    grade: 'E135',
    fc: 30.4,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(2層)',
    grade: 'E120',
    fc: 27.4,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(2層)',
    grade: 'E105',
    fc: 25.5,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(2層)',
    grade: 'E95',
    fc: 23.6,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(2層)',
    grade: 'E85',
    fc: 22.1,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(2層)',
    grade: 'E75',
    fc: 20.3,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(2層)',
    grade: 'E65',
    fc: 18.8,
  },
  {
    standard: 'JAS同一等級構成集成材',
    species: '(2層)',
    grade: 'E55',
    fc: 16.9,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '180E',
    fc: 46.8,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '180E',
    fc: 45.0,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '180E',
    fc: 42.0,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '160E',
    fc: 41.4,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '160E',
    fc: 40.2,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '160E',
    fc: 37.2,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '140E',
    fc: 36.0,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '140E',
    fc: 34.8,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '140E',
    fc: 32.4,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '120E',
    fc: 31.2,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '120E',
    fc: 30.0,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '120E',
    fc: 27.6,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '110E',
    fc: 28.2,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '110E',
    fc: 27.0,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '110E',
    fc: 25.8,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '100E',
    fc: 25.8,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '100E',
    fc: 25.2,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '100E',
    fc: 23.4,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '90E',
    fc: 23.4,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '90E',
    fc: 22.8,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '90E',
    fc: 21.0,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '80E',
    fc: 21.0,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '80E',
    fc: 19.8,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '80E',
    fc: 18.6,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '70E',
    fc: 18.0,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '70E',
    fc: 17.4,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '70E',
    fc: 16.2,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '60E',
    fc: 15.6,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '60E',
    fc: 15.0,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '60E',
    fc: 13.8,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '50E',
    fc: 12.7,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '50E',
    fc: 12.3,
  },
  {
    standard: 'JASA種構造用単板積層材',
    species: 'None',
    grade: '50E',
    fc: 11.1,
  },
]
